version: '3'

services:
  composer:
    image: composer:latest
    working_dir: /app
    volumes:
      - ./:/app
    env_file:
      - .env
    user: ${HOST_UID}:${HOST_GID}

  php:
    image: php:8.0-cli-alpine
    working_dir: /app
    volumes:
      - ./:/app
    env_file:
      - .env
    user: ${HOST_UID}:${HOST_GID}
